version: '3'
services:

  db:
    restart: always
    image: mysql:8
    env_file: .env.production
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql-backward-compatibility.cnf:/etc/mysql/conf.d/backward-compatibility.cnf

  stratum-mining:
    restart: always
    build: stratum-mining
    image: mecab/stratum-mining
    env_file: .env.production
    ports:
      - "16011:16011"
    depends_on:
      - db
    volumes:
      - ./stratum-mining/conf/config.py:/work/stratum-mining/conf/config.py
      - ./logs_stratum-mining:/work/stratum-mining/log

  stratum-mining-low-difficulty:
    restart: always
    build: stratum-mining
    image: mecab/stratum-mining
    env_file: .env.production
    ports:
      - "16012:16012"
    depends_on:
      - db
    volumes:
      - ./stratum-mining/conf/config_low_difficulty.py:/work/stratum-mining/conf/config.py
      - ./logs_stratum-mining:/work/stratum-mining/log

  mpos:
    restart: always
    build: mpos
    image: mecab/mpos
    env_file: .env.production
    volumes:
      - ./mpos/config:/app/include/config
      - ./logs_mpos:/app/logs
    depends_on:
      - stratum-mining
      - db
    ports:
      - "16010:80"
